import { requiredElement } from "../../core/dom.js";

export type DashboardDomElements = {
  stationSelect: HTMLSelectElement;
  historyYearsSelect: HTMLSelectElement;
  statusEl: HTMLParagraphElement;
  errorBannerEl: HTMLParagraphElement;
  toastEl: HTMLDivElement;
  toastTextEl: HTMLParagraphElement;
  toastCloseBtn: HTMLButtonElement;
  playbackWindowLabelEl: HTMLParagraphElement;
  resultsSkeletonEl: HTMLDivElement;
  metricsGridEl: HTMLDivElement;
  summaryOutputEl: HTMLTableSectionElement;
  rowsOutputEl: HTMLTableSectionElement;
  windChartCanvas: HTMLCanvasElement;
  weatherChartCanvas: HTMLCanvasElement;
  roseChartCanvas: HTMLCanvasElement;
  timeframeTrendWrapEl: HTMLDivElement;
  timeframeTrendCanvas: HTMLCanvasElement;
  queryProgressWrap: HTMLDivElement;
  queryProgressBar: HTMLProgressElement;
  queryProgressText: HTMLParagraphElement;
  playbackProgressBar: HTMLProgressElement;
  playbackProgressText: HTMLParagraphElement;
  playbackProgressWrap: HTMLDivElement;
  decisionCardEl: HTMLDivElement;
  mapPlaybackShellEl: HTMLDivElement;
  chartsSectionEl: HTMLDivElement;
  timeframeSectionEl: HTMLDivElement;
  rawCardEl: HTMLDivElement;
  windChartCardEl: HTMLDivElement;
  weatherChartCardEl: HTMLDivElement;
  roseChartCardEl: HTMLDivElement;
  decisionUpdatedEl: HTMLParagraphElement;
  decisionBadgeEl: HTMLSpanElement;
  decisionWindEl: HTMLParagraphElement;
  decisionQualityEl: HTMLParagraphElement;
  decisionRiskEl: HTMLParagraphElement;
  playbackPlayBtn: HTMLButtonElement;
  playbackSlider: HTMLInputElement;
  playbackStepSelect: HTMLSelectElement;
  playbackSpeedSelect: HTMLSelectElement;
  playbackLoopInput: HTMLInputElement;
  playbackStatusEl: HTMLParagraphElement;
  overlayTempInput: HTMLInputElement;
  overlayPressureInput: HTMLInputElement;
  overlayTrailInput: HTMLInputElement;
  timeframeGroupingSelect: HTMLSelectElement;
  timeframeRunBtn: HTMLButtonElement;
  timeframeStatusEl: HTMLParagraphElement;
  timeframeCardsEl: HTMLDivElement;
  timeframeComparisonEl: HTMLDivElement;
  timeframeGenerationEl: HTMLParagraphElement;
  toggleTablesButton: HTMLButtonElement;
  tablesPanelEl: HTMLDivElement;
  exportCsvButton: HTMLButtonElement;
  exportParquetButton: HTMLButtonElement;
  exportPdfButton: HTMLButtonElement;
  authUserEl: HTMLSpanElement;
  authLogoutBtn: HTMLButtonElement;
};

export function getDashboardDomElements(): DashboardDomElements {
  return {
    stationSelect: requiredElement<HTMLSelectElement>("station"),
    historyYearsSelect: requiredElement<HTMLSelectElement>("history-years"),
    statusEl: requiredElement<HTMLParagraphElement>("status"),
    errorBannerEl: requiredElement<HTMLParagraphElement>("error-banner"),
    toastEl: requiredElement<HTMLDivElement>("app-toast"),
    toastTextEl: requiredElement<HTMLParagraphElement>("app-toast-text"),
    toastCloseBtn: requiredElement<HTMLButtonElement>("app-toast-close"),
    playbackWindowLabelEl: requiredElement<HTMLParagraphElement>("playback-window-label"),
    resultsSkeletonEl: requiredElement<HTMLDivElement>("results-skeleton"),
    metricsGridEl: requiredElement<HTMLDivElement>("metrics-grid"),
    summaryOutputEl: requiredElement<HTMLTableSectionElement>("summary-output"),
    rowsOutputEl: requiredElement<HTMLTableSectionElement>("rows-output"),
    windChartCanvas: requiredElement<HTMLCanvasElement>("wind-chart"),
    weatherChartCanvas: requiredElement<HTMLCanvasElement>("weather-chart"),
    roseChartCanvas: requiredElement<HTMLCanvasElement>("rose-chart"),
    timeframeTrendWrapEl: requiredElement<HTMLDivElement>("timeframe-trend-wrap"),
    timeframeTrendCanvas: requiredElement<HTMLCanvasElement>("timeframe-trend-chart"),
    queryProgressWrap: requiredElement<HTMLDivElement>("query-progress-wrap"),
    queryProgressBar: requiredElement<HTMLProgressElement>("query-progress-bar"),
    queryProgressText: requiredElement<HTMLParagraphElement>("query-progress-text"),
    playbackProgressBar: requiredElement<HTMLProgressElement>("playback-progress-bar"),
    playbackProgressText: requiredElement<HTMLParagraphElement>("playback-progress-text"),
    playbackProgressWrap: requiredElement<HTMLDivElement>("playback-progress-wrap"),
    decisionCardEl: requiredElement<HTMLDivElement>("decision-card"),
    mapPlaybackShellEl: requiredElement<HTMLDivElement>("map-playback-shell"),
    chartsSectionEl: requiredElement<HTMLDivElement>("charts-section"),
    timeframeSectionEl: requiredElement<HTMLDivElement>("timeframe-section"),
    rawCardEl: requiredElement<HTMLDivElement>("raw-card"),
    windChartCardEl: requiredElement<HTMLDivElement>("wind-chart-card"),
    weatherChartCardEl: requiredElement<HTMLDivElement>("weather-chart-card"),
    roseChartCardEl: requiredElement<HTMLDivElement>("rose-chart-card"),
    decisionUpdatedEl: requiredElement<HTMLParagraphElement>("decision-updated"),
    decisionBadgeEl: requiredElement<HTMLSpanElement>("decision-badge"),
    decisionWindEl: requiredElement<HTMLParagraphElement>("decision-wind"),
    decisionQualityEl: requiredElement<HTMLParagraphElement>("decision-quality"),
    decisionRiskEl: requiredElement<HTMLParagraphElement>("decision-risk"),
    playbackPlayBtn: requiredElement<HTMLButtonElement>("playback-play"),
    playbackSlider: requiredElement<HTMLInputElement>("playback-slider"),
    playbackStepSelect: requiredElement<HTMLSelectElement>("playback-step"),
    playbackSpeedSelect: requiredElement<HTMLSelectElement>("playback-speed"),
    playbackLoopInput: requiredElement<HTMLInputElement>("playback-loop"),
    playbackStatusEl: requiredElement<HTMLParagraphElement>("playback-status"),
    overlayTempInput: requiredElement<HTMLInputElement>("overlay-temperature"),
    overlayPressureInput: requiredElement<HTMLInputElement>("overlay-pressure"),
    overlayTrailInput: requiredElement<HTMLInputElement>("overlay-trail"),
    timeframeGroupingSelect: requiredElement<HTMLSelectElement>("timeframe-grouping"),
    timeframeRunBtn: requiredElement<HTMLButtonElement>("timeframe-run"),
    timeframeStatusEl: requiredElement<HTMLParagraphElement>("timeframe-status"),
    timeframeCardsEl: requiredElement<HTMLDivElement>("timeframe-cards"),
    timeframeComparisonEl: requiredElement<HTMLDivElement>("timeframe-comparison"),
    timeframeGenerationEl: requiredElement<HTMLParagraphElement>("generation-summary"),
    toggleTablesButton: requiredElement<HTMLButtonElement>("toggle-tables"),
    tablesPanelEl: requiredElement<HTMLDivElement>("tables-panel"),
    exportCsvButton: requiredElement<HTMLButtonElement>("export-csv"),
    exportParquetButton: requiredElement<HTMLButtonElement>("export-parquet"),
    exportPdfButton: requiredElement<HTMLButtonElement>("export-pdf"),
    authUserEl: requiredElement<HTMLSpanElement>("auth-user"),
    authLogoutBtn: requiredElement<HTMLButtonElement>("auth-logout"),
  };
}
